### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by August66** [gyy8426/OS-SGG#1]
It can not reach the precision mentioned in the paper, which is 3 points lower than the recall rate of the paper.Can you direct me to your parameter setting?

**Comment by gyy8426** [comment]
The hyper-parameters  are set as follows:
num_gpus : 1
num_workers : 1
lr : 0.005
batch_size : 16
val_size : 5000
l2 : 0.0001
clip : 5.0
print_interval : 100
mode : sgcls
model : gkg
old_feats : False
order : leftright
cache : 
gt_box : False
adam : False
test : False
multi_pred : False
num_epochs : 6
use_resnet : False
use_proposals : False
nl_obj : 0
nl_edge : 12
nh_obj : 0
nh_edge : 12
nl_obj_gcn : 0
nl_edge_gcn : 4
hidden_dim : 768
pooling_dim : 4096
pass_in_obj_feats_to_decoder : False
pass_in_obj_feats_to_edge : False
rec_dropout : 0.1
use_bias : True
use_tanh : False
limit_vision : False
bg_num_rel : 2
test_alpha : 1.0
debug : False.  
You can directly test our pre-trained model with the link mentioned in ReadMe.
``nledge12_nhedge12_edgegcn4_conceptgcn2Glove_drop3ex2mat_sum_drop6cptmat_dirso_sum_dropgcn_BiasDrop3_lr5e3_b16_vgg_oneshot''
